name: ddr_est
channels:
  - conda-forge
dependencies:
  - python >=3.7
  - numpy
  - scipy
  - pandas
  - tabulate


  # Testing infrastructure
  - pytest
  - pytest-cov

  # Tools
  - black
  - flake8
  - pdbpp==0.10.3
  - pre-commit
  - toml
  - tqdm

  # Plotting
  - matplotlib
  - seaborn
  - jinja2

   # JAX
  - pip:
      - jaxlib==0.4.33
      - jax==0.4.33
      - -e ./submodules/durable/
      - -e .
